In [3]:
import torch
from torch import nn
import math
from torch import functional as F

In [ ]:
class selfAttention(nn.Module):
    def __init__(self, hidden_dim:int = 728)->None:
        super().__init__()
        self.hidden_dim = hidden_dim
    #初始化qkv
        self.query_proj = nn.Linear(hidden_dim,hidden_dim)
        self.key_proj = nn.Linear(hidden_dim,hidden_dim)
        self.value_proj = nn.Linear(hidden_dim,hidden_dim)
    
    def forward(self,X):
        # Q : (batch_size,seq_len,dim)
        # K*T:(batch_size,dim,seq_len)
        Q = self.query_proj(X)
        K = self.key_proj(X)
        V = self.value_proj(X)

        attention_value = torch.matmul(
            #给k转置
            Q,K.transpose(-1,-2)
        )

        attention_softmax = torch.softmax(
            attention_value / math.sqrt(self.hidden_dim),dim=-1
        )

        result = torch.matmul(
            attention_softmax,V
        )
        return result

X = torch.rand(2,3,4)


self_att_test = selfAttention(4)
self_att_test(X)


tensor([[[-0.1647, -0.5922,  0.2470, -0.0232],
         [-0.1650, -0.5883,  0.2439, -0.0200],
         [-0.1641, -0.5926,  0.2476, -0.0244]],

        [[-0.2515, -0.7480,  0.2592, -0.1423],
         [-0.2503, -0.7461,  0.2571, -0.1425],
         [-0.2504, -0.7468,  0.2562, -0.1411]]], grad_fn=<UnsafeViewBackward0>)

In [40]:
class selfAttentionV2(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim
        self.qkv = nn.Linear(dim,dim*3)

    def forward(self,X):
        # 
        QKV = self.qkv(X)
        Q,K,V = torch.split(QKV,self.dim,dim=-1)

        result = torch.softmax(torch.matmul(
            Q,K.transpose(-1,-2)
        ) / math.sqrt(self.dim),dim=-1
        )
        print(result)
        output = result @ V
        return output
X = torch.rand(3,2,4)
model2 = selfAttentionV2(4)
model2(X)


tensor([[[0.4894, 0.5106],
         [0.5109, 0.4891]],

        [[0.5137, 0.4863],
         [0.4978, 0.5022]],

        [[0.5048, 0.4952],
         [0.5059, 0.4941]]], grad_fn=<SoftmaxBackward0>)


tensor([[[-0.4449,  0.2280, -0.5718,  0.0779],
         [-0.4421,  0.2280, -0.5792,  0.0705]],

        [[-0.5378,  0.1127, -0.5518,  0.1663],
         [-0.5330,  0.1195, -0.5498,  0.1640]],

        [[-0.5221,  0.0467, -0.6415,  0.1114],
         [-0.5225,  0.0464, -0.6415,  0.1117]]], grad_fn=<UnsafeViewBackward0>)

In [ ]:
class MutiheadTransformer(nn.Module):
    def __init__(self,head_num,hidden_dim,drop_out = 0.1):
        super().__init__()
        self.head_num = head_num
        self.hidden_dim = hidden_dim
        self.head_dim = hidden_dim // head_num
        self.q_proj = nn.Linear(hidden_dim,hidden_dim)
        self.k_proj = nn.Linear(hidden_dim,hidden_dim)
        self.v_proj = nn.Linear(hidden_dim,hidden_dim)

        self.drop_out = nn.Dropout(drop_out)
        
        self.out_proj = nn.Linear(hidden_dim,hidden_dim)

    def forward(self,X,hidden_mask = None):
        #   qkv (batch,s,h)  ->   (batch,head_num,s,head_dim)
        batch , seq , _ =  X.size()
        Q = self.q_proj(X)
        K = self.k_proj(X)
        V = self.v_proj(X)

        #   transform it's shape (batch,s,head_num,head_dim)  (batch,head_num,s,head_dim)
        q = Q.view(batch,seq,self.head_num,self.head_dim).transpose(1,2)   
        k = K.view(batch,seq,self.head_num,self.head_dim).transpose(1,2)   
        v = V.view(batch,seq,self.head_num,self.head_dim).transpose(1,2)  

        result_mid = (q @ k.transpose(-1,-2)) / math.sqrt(self.head_dim)

        if hidden_mask is not None:
            result_mid = result_mid.masked_fill(
                hidden_mask == 0 , float('-inf') #   无限小的值
            )
        print(result_mid)

        #   对行向量进行softmax
        result_mid = torch.softmax(result_mid,dim=-1)
        result_drop = self.drop_out(result_mid)

        output_mid = (result_drop @ v).transpose(1,2).contiguous()
        output_mid = output_mid.view(batch,seq,-1)#h

        output = self.out_proj(output_mid)
        return output

mask = torch.tensor([
    [1,0],
    [0,0],
    [1,1]
]).unsqueeze(1).unsqueeze(2).expand(3,8,2,2)
print(mask.shape)
X = torch.rand(3,2,128)
model = MutiheadTransformer(8,128)# 8 head
model(X,mask)

In [ ]:
class SimpleDecoder(nn.Module):
    def __init__(self,hidden_dim,head_num,dropout_rate=0.1):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.head_num = head_num
        self.head_dim = hidden_dim // head_num
        self.dropout_rate = dropout_rate

        self.q_proj = nn.Linear(hidden_dim,hidden_dim)
        self.k_proj = nn.Linear(hidden_dim,hidden_dim)
        self.v_proj = nn.Linear(hidden_dim,hidden_dim)

        # upgrade dimension 
        self.up = nn.Linear(hidden_dim,hidden_dim*4)
        self.down = nn.Linear(hidden_dim * 4 , hidden_dim)
        self.act_proj = nn.ReLU()
        # dropout
        self.dropout_proj = nn.Dropout(dropout_rate)
        self.layerNorm_proj = nn.LayerNorm(hidden_dim,eps=0.000001)


    def attention_layer(self,q,k,v,mask,):
        # (batch,seq,head_num,head_dim) -> (batch,head_num,seq,head_dim)
        attention_mid = (q @ k.transpose(-1,-2)) / math.sqrt(self.head_dim)
        # Itself tril and original mask
        if mask is not None:
            mask = mask.tril()
            attention_mid = attention_mid.masked_fill(
                mask == 0 , float('-inf')
            )
        else:
            # make a ones trangles matrix which dimensions same like original 
            mask = attention_mid.ones_like().tril()
            attention_mid = attention_mid.masked_fill(
                mask == 0 , float('-inf')
            )
        # Specify a dimension row
        attention_mid = torch.softmax(attention_mid,dim=-1)
        # dropout layer
        attention_dropout = self.dropout_proj(self.dropout_rate)
        
        #(batch,head_num,seq,head_dim)
        output = (attention_dropout @ v)


        return output


    def ffn(self,X):
        up = self.up(X)
        up = self.act_proj(X)
        down = self.down(up)

        dropout = self.dropout_proj(down)

        return self.layerNorm_proj(dropout + X)

    def mha(self,X,mask):
        batch,seq,_ = X.size()
        Q = self.q_proj(X)
        K = self.k_proj(X)
        V = self.v_proj(X)
        # (batch,seq,hidden_dim) -> (batch,seq,head_num,head_dim)
        q = Q.view(batch,seq,self.head_num,-1).transpose(1,2)
        k = K.view(batch,seq,self.head_num,-1).transpose(1,2)
        v = V.view(batch,seq,self.head_num,-1).transpose(1,2)

        attention = self.attention_layer(q,k,v,mask).transpose(1,2).contiguous()
        output = attention.view(batch,seq,-1)
        return output

    def forward(self,X,attention_mask=None):
        X = self.mha(X,attention_mask)
        X = self.ffn(X)
        
        return X