In [3]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from dataclasses import dataclass


In [ ]:
test = torch.tensor([[0,1],
                    [4,3],
                    [5,4],
                    [0,0]])
print(test.shape)
test = test.reshape(2,-1)
print(test)
idx,topx = torch.where(test)
idx,topx

hot = torch.tensor([[1,0],[0,0]])

torch.Size([4, 2])
tensor([[0, 1, 4, 3],
        [5, 4, 0, 0]])


(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 0, 1]))

In [ ]:
import torch

routing_probs = torch.tensor([
    [0.1, 0.4, 0.3, 0.2],  # 第一个 token 的 4 个专家概率
    [0.2, 0.1, 0.5, 0.2],  # 第二个 token 的 4 个专家概率
])  # shape = (2, 4), 假设 batch_size * seq_len = 2, expert_number = 4
# (4,2)
top_k = 2

router_weights, selected_experts = torch.topk(routing_probs, top_k, dim=-1)

print("router_weights:\n", router_weights)
print("selected_experts:\n", selected_experts)
print(routing_probs.shape,selected_experts.shape)

mask = F.one_hot(selected_experts,4)

print("未反转的矩阵:# shape(batch * seq,topx,expert_num)\n",mask)
mask = mask.permute(2,1,0)

print("原始反转矩阵:# shape(expert_num,topx,batch * seq)\n",mask)
choose = mask[1]
print("第二个专家的矩阵:(topx,batch * seq)\n",choose)
idx, topx = torch.where(choose)
print(idx,topx)
#(2,2)

router_weights:
 tensor([[0.4000, 0.3000],
        [0.5000, 0.2000]])
selected_experts:
 tensor([[1, 2],
        [2, 0]])
torch.Size([2, 4]) torch.Size([2, 2])
未反转的矩阵:# shape(batch * seq,topx,expert_num)
 tensor([[[0, 1, 0, 0],
         [0, 0, 1, 0]],

        [[0, 0, 1, 0],
         [1, 0, 0, 0]]])
原始反转矩阵:# shape(expert_num,topx,batch * seq)
 tensor([[[0, 0],
         [0, 1]],

        [[1, 0],
         [0, 0]],

        [[0, 1],
         [1, 0]],

        [[0, 0],
         [0, 0]]])
第二个专家的矩阵:(topx,batch * seq)
 tensor([[1, 0],
        [0, 0]])
tensor([0]) tensor([0])


In [46]:
test = torch.tensor([1,2,3])
b = torch.tensor([2])
a = b*test
b.shape,test.shape,

(torch.Size([1]), torch.Size([3]))